### ISSUE TITLE
Labels are missing in Firefox

### ISSUE THREAD

**Issue by WeslleyDeSouza** [oblique-bit/oblique#101]
Issue on firefox:
![image](https://github.com/oblique-bit/oblique/assets/20669525/618fd51b-3952-48dd-a7d9-e87c4aa8fbc6)

File:
https://github.com/oblique-bit/oblique/blob/42d05cb6722009da45b66d41dadd73973ff8ab2d/projects/oblique/src/styles/scss/material/_mat-form-field.scss

Current:
```
.mat-form-field-label {
			margin-top: 1px; // empiric value
			line-height: 1;
			overflow-x: clip;
			overflow-y: visible;
		}
```

Possible solution:
(Not Tested on IOS/Safari)
``` 
.mat-form-field-label {
			margin-top: 1px; // empiric value
			line-height: 1;
			overflow-y: visible;
			overflow-x: hidden;
			min-height: -webkit-fill-available;
                        min-height: -moz-available;
		}
```

![image](https://github.com/oblique-bit/oblique/assets/20669525/4c10a314-9c5a-41b4-a03c-145ddd36e81a)

Notes to: @milan-ka-sk 
```
 @-moz-document url-prefix() {
.mat-form-field-label {
			margin-top: 1px; // empiric value
			line-height: 1;
			overflow-y: visible;
			 overflow-x: unset
			min-height: -webkit-fill-available;
                        min-height: -moz-available;
		}
} 
```

**Comment by milan-ka-sk** [comment]
We have the same and have made a hotfix inspired by Weslleys suggestion for now.
Please make also sure that the inputs are behaving correctly also when tabbing through them if there are more of them in a group --> TAB pressed, the next one shall get the focus. With Weslley suggestion, one must press TAB 2x to get to the next input because when pressing it once the label element inside gets the focus.

Our solution:

`@-moz-document url-prefix() {
    // target only FF: see: https://www.geeksforgeeks.org/targeting-only-firefox-with-css/

    .mat-form-field.mat-form-field-appearance-outline .mat-form-field-label {
        overflow-x: hidden;
        min-height: -webkit-fill-available;
        min-height: -moz-available;

        // when TABing through fix (still there is a bug, difficult to solve, one must TAB 2x to move)
        &:focus-visible {
            outline: none;
        }
    }

}`

**Comment by WeslleyDeSouza** [comment]
@milan-ka-sk 
Hey Milan, can you provide an snippet `if there are more of them in a group` ?
i would like to test this in our application but i could not reproduce the issue..
