### ISSUE TITLE
Sticky component in responsive mode has no borders

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#102]
Hello Oblique team, 

The sticky component has it's border disappearing when we are in mobile mode. https://oblique.bit.admin.ch/components/sticky
Normal view 
![image](https://github.com/oblique-bit/oblique/assets/3356843/218eecd0-66b1-4115-b642-9acc84fe8e45)

Mobile view
![image](https://github.com/oblique-bit/oblique/assets/3356843/ba74b4c2-0b2d-4c70-9792-8f3f0206c684)

Was this behavior expected? (If yes then I have to override this behavior for my project)

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-2372.

Kind regards

**Comment by gillerr** [comment]
Hi @ice-blaze 

This actually works as designed as the sticky component does nothing on mobile view. This means the borders don't delimit the scrollable area anymore and thus aren't shown. I do agree that the documentation could be improved in this regard.

The idea is to prevent valuable space from being blocked on a small screen. The sticky header and footer do reduce the usable area of the screen. While not a problem on a desktop, this can render an application inoperable on a mobile or tablet.

This component is a relic of a distant past where flexbox did not exist. Nowadays it is quite easy to achieve the same thing with more flexibility  using flexbox. Moreover its name is confusing as it doesn't work like the `position: sticky` CSS property at all. This is why it has been deprecated with Oblique 10.3.0

**Comment by ice-blaze** [comment]
Erf we are using it x) But ok thanks for your explanations.
