### ISSUE TITLE
Vertical Stepper - trailing line if the last step text is too long

### ISSUE THREAD

**Issue by milan-ka-sk** [oblique-bit/oblique#104]
Not sure if it is an issue or just a design preference, but there is this trailing line in the vertical stepper at the bottom, when the last step text is too long. 

Expected behaviour (my opinion): no trailing line

in the docs..
![image](https://github.com/oblique-bit/oblique/assets/17095574/058e6a2a-7f2b-4a48-b205-d6a663b114ce)

in real life project
![image](https://github.com/oblique-bit/oblique/assets/17095574/44392c4f-e612-4eeb-9bed-44ab18b102c2)

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-2374.

Kind regards
