### ISSUE TITLE
Carets in ObNavTreeComponent wrong way round

### ISSUE THREAD

**Issue by tja-bit** [oblique-bit/oblique#107]
Hello Oblique-Team

We discovered that the icons used in ObNavTreeComponent to indicate child-pages are displayed the wrong way round - counterintuitive.

Whenever the child nodes are shown, the caret is oriented to the right. When the child nodes are hidden the caret is oriented down. This is against the expectations of the users:

![image](https://github.com/oblique-bit/oblique/assets/139466439/216c805e-0476-4d7e-9e66-5d0d5694a821)

Intuitively you would expect that a caret pointing to the right is displayed, when the cild nodes are hidden and vice versa.

In the latest Sketch Styleguide the icons behave as expected:

![image](https://github.com/oblique-bit/oblique/assets/139466439/a3a8565e-6366-49ba-a699-fa4a6654e3f4)

Thanks in advance

Best Regards
Tobias

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-2233.

Kind regards

**Comment by nina-egger** [comment]
This has been fixed in 10.2.0
