### ISSUE TITLE
Spinner issue on startup

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#11]
Hi,

I tried to use two spinners that should show the loading of a slow API request. But I have an issue where I can't activate them in my `ngOnInit()` So my workaround is something like that but I would consider it as quite ugly.

```typescript
    setTimeout((time) => {
      this.obSpinnerService.activate(this.REALEASE_NOTES_CHANNEL);
    }, 1);
```

On mac, chrome handle it really fast but firefox which seems slower shows blinking which is not very clean. Any insight or knowledge of a `deactivate()` broadcasted to all spinners?

**Comment by ice-blaze** [comment]
I found a cleaner way to do the workaround using the `ngAfterViewInit()` function to start the spinners instead of the "ugly" `setTimeout(...,1)`

**Comment by gillerr** [comment]
Hello

The only Oblique's feature that deactivates the spinner is the ObHttpApiInterceptor. But it ensures that the spinner is only deactivated once no request are in flight. Is the ObHttpApiInterceptor used in your application?

Actually, which version of Oblique & Angular are you using?
