### ISSUE TITLE
ObINavigationLink - children in children

### ISSUE THREAD

**Issue by eltigree** [oblique-bit/oblique#113]
At the moment i can't add children under children in ObINavigationLink. I can not use tree navigation for that...

        this.navigation.push(
          { label: "i18n.application.tabCustomers.title", url: 'customers',
            children: [
              {
                url: 'usermgmt',
                label: "i18n.application.tabCustomersUsermgmt.title",
              },
              {
                url: null,
                label: "i18n.application.tabCustomersQSBenefit.title",
                --->>>> not working 
                children: [{
                  url: 'facturationamt',
                  label: "i18n.application.tabCustomersQSFacturationAmt.title",
                  icon: "space"
                },
                  {
                    url: 'exportverrrechnung',
                    label: "i18n.application.tabExportVerrechnung.title",
                    icon: "space"
                  },
                  {
                    url: 'verrechnungStichtage',
                    label: "i18n.application.tabVerrechnungStichtage.title",
                    icon: "space"
                  }]
              }

Have you some ideas for this or have you something in your pipe line about this?

**Comment by nina-egger** [comment]
Hello!

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-2411

Kind regards

**Comment by nina-egger** [comment]
This has been fixed in Oblique 11.0.0
