### ISSUE TITLE
Hamburger button and tabs not visible at specific width

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#114]
Hello Oblique,

When the width of window is 905px it seems that the tabs are missing and the hamburger button not visible. You can reproduce it on https://oblique.bit.admin.ch/components.
OS: MacOS
Browser: Chrome
![image](https://github.com/oblique-bit/oblique/assets/3356843/5f36844c-3e19-4850-9961-ef2fdd1cfd65)

**Comment by nina-egger** [comment]
Hello @ice-blaze!

I don't have a Mac to see if I can reproduce it so I checked on Edge and Windows and it looked ok.
<img width="953" alt="image" src="https://github.com/oblique-bit/oblique/assets/18281756/16d45489-71f2-4be3-8b3c-2c6c829065dd">

Can you check if you can reproduce the issue in another browser? Or on another device? I have a feeling this is either browser or device specific.

Regards
Nina

**Comment by ice-blaze** [comment]
I can confirm, on firefox/edge for MacOS and firefox on Windows. Edge on windows I couldn't reproduce but I have the feeling that the increments go from 904-905.6. And if it's 905.6 and check in the console with  `document.documentElement.scrollWidth` it equals 906 which is too much (the issue seems to be visible only on 905)

**Comment by nina-egger** [comment]
Created a ticket for this. Ticket number is OUI-2556
Kind Regards

**Comment by nina-egger** [comment]
Fixed with Version 11.0.1
