### ISSUE TITLE
Stackblitz for demo (feature proposal)

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#117]
Hello Oblique team,

I created a stackblitz with angular and oblique installed. It's very useful for testing and show simple examples with the problems. I open this issue to maybe have a talk to add this in the documentation
https://stackblitz.com/edit/stackblitz-starters-okuhyg?file=package.json

**Comment by nina-egger** [comment]
This is only planned for the new documentation. (With Oblique 11)

**Comment by ice-blaze** [comment]
@nina-egger  I had more in mind for a bug context. Asking people to reproduce the bug inside a clean stackblitz with already oblique installed in it. In that sense, we could avoid the hypothesis that it comes from their project and not oblique itself. 

(I think it's also super nice to have it in all documentation)

**Comment by nina-egger** [comment]
@ice-blaze something for the bug report templates then. I will forward this. Thank you!

**Comment by swiss-design-system** [comment]
@ice-blaze We got a bug template now here on our new support page: https://oblique.bit.admin.ch/introductions/support 

Can this issue be closed?

**Comment by ice-blaze** [comment]
@swiss-design-system all good, thanks (y)
