### ISSUE TITLE
Notification timeout is twice as long

### ISSUE THREAD

**Issue by kervantas** [oblique-bit/oblique#12]
Hello!

We have encountered an issue; the notifications will not disappear after the configured time, instead they will stay up for twice as long.

You can check it here: [https://oblique.bit.admin.ch/components/notification?theme=material](https://oblique.bit.admin.ch/components/notification?theme=material)
The default timeout is 3500ms, but the notification will disappear after 7000ms.

**Comment by gillerr** [comment]
Thank you for your feedback. I was able to spot and fix the problem, This will be released with the next version.

**Comment by gillerr** [comment]
shipped with Oblique 6.0.0
