### ISSUE TITLE
button margin 0?

### ISSUE THREAD

**Issue by WeslleyDeSouza** [oblique-bit/oblique#120]
Is there a reason why "button" needs to have an margin property?

![image](https://github.com/oblique-bit/oblique/assets/20669525/26f08217-9c83-404c-98e2-832b03764ae8)

The margin property here is obsolete and causes now us/me to use margin attribute with an !important flag or reorder the css imports.. 

![image](https://github.com/oblique-bit/oblique/assets/20669525/9f6f0365-a44f-4f0e-8c4e-0c5f7a36e7ca)

![image](https://github.com/oblique-bit/oblique/assets/20669525/d2033e8b-275b-4439-af47-6145286d41c7)

**Comment by nina-egger** [comment]
Hello @WeslleyDeSouza, could you tell me which versions of Oblique / Angular you're using? Then I can check our history for the reason.

Kind Regards
Nina

**Comment by WeslleyDeSouza** [comment]
@nina-egger Hi Nina,
Well its also on the Oblique website, so i assume its on the latest version as well.
![image](https://github.com/oblique-bit/oblique/assets/20669525/7d9c470d-ad5e-4dcd-bd04-1ad38e37b5dd)

**Comment by nina-egger** [comment]
@WeslleyDeSouza Should no longer be the case in Oblique v11 from what I can see. So your problem will be solved.
