### ISSUE TITLE
Service Navigation Module is always active

### ISSUE THREAD

**Issue by daniel-va** [oblique-bit/oblique#126]
### Oblique version

11.0.1

### Browser & version

Microsoft Edge 123.0.2420.81 (Official build) (64-bit)

### Node version

v20.11.1

### Device and operating system

Microsoft Windows 10 Enterprise

### Is this a regression?

I don't know

### Screenshots

![image](https://github.com/oblique-bit/oblique/assets/15192000/bc12a8cc-5abc-4453-bf0d-f55caf61b1fb)

### Description
Oblique throws an error if it is used on any domains that are not `localhost`, `127.0.0.1` or a subdomain of `admin.ch`. This happens even in minimal setups, where the only manually included Oblique module is the `ObMasterLayoutModule`.

### Reproduction

Open any application using Oblique on a Domain that is not `localhost`, `127.0.0.1` or `admin.ch`.
A minimal reproducible example, using just the application generated by Oblique's "Getting started", can be found here:
https://github.com/daniel-va/oblique-domain-bug-example

To get the error run `npm run start` and access `:4200` over your computer's public IP.

### Expected behaviour
No error is thrown.

### Context
The [Service Navigation Module](https://github.com/oblique-bit/oblique/blob/master/projects/oblique/src/lib/service-navigation/service-navigation.module.ts) contains the [ObServiceNavigationTimeoutCookieService](https://github.com/oblique-bit/oblique/blob/master/projects/oblique/src/lib/service-navigation/timeout/service-navigation-timeout-cookie.service.ts).
When loading a page using Oblique, that service will always check if the current domain is "valid", and throw an error if not.

The Service Navigation Module is always implicitly imported by the [ObMasterLayoutModule](https://github.com/oblique-bit/oblique/blob/master/projects/oblique/src/lib/master-layout/master-layout.module.ts). This causes the check in `ObServiceNavigationTimeoutCookieService` to always be executed, as long as the master layout is imported.

### Proposed solution

Either:
- Remove the import of `ObServiceNavigationModule` from `ObMasterLayoutModule`
- Don't run `ObServiceNavigationTimeoutCookieService` unless explicitly activated
- Relax/Remove the domain check in `ObServiceNavigationTimeoutCookieService`

**Comment by nina-egger** [comment]
Hello @daniel-va !

Thank you for your report. This is a known issue and a fix is already planned for Oblique 11.0.2.  The fix will make sure cookie activity is only monitored if PAMS is actually activated. You should no longer see the error after that.

Note: tracked in task OUI-3014

**Comment by nina-egger** [comment]
This has been fixed with the version 11.0.2
