### ISSUE TITLE
When changing the width of the browser too fast, the service-navigation get's issues

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#127]
### Oblique version

11.1.3

### Browser & version

Chrome 124.0.6367.208

### Device and operating system

osx 14.4.1

### Is this a regression?

No

### Screenshots

![image](https://github.com/oblique-bit/oblique/assets/3356843/71350aae-5447-495a-8cbc-6f25cddf977e)
![image](https://github.com/oblique-bit/oblique/assets/3356843/bf874c84-98a6-4aa4-b5c3-297b31c1ea6c)

### Description

```true
When rotating an iPad you get the bug within the service-navigation. The layout looks odd.
```

### Reproduction

```true
* Open chrome
* Open dev tools
* Use ipad pro resolution
* click on the applications of the service-navigation
* rotate the ipad through the dev tools
```

### Expected behaviour

```true
There shouldn't be a scroll appearing.
```

**Comment by nina-egger** [comment]
Than you for your report. 
This issue will be tracked in the Jira ticket OUI-3100
