### ISSUE TITLE
Footer Logo

### ISSUE THREAD

**Issue by BenjaminHofstetter** [oblique-bit/oblique#135]
### Oblique version

11.3.2

### Browser & version

Chrome 128.0.6613.85

### Node version

20.13.1

### Device and operating system

MacOS 14.6.1 

### Is this a regression?

No

### Screenshots

Big screen with MasterLayoutConfig.footer.hasLogoOnScroll = true;
This is ok
<img width="395" alt="Screenshot 2024-08-23 at 11 17 50" src="https://github.com/user-attachments/assets/81887d69-f8e4-4694-beda-e6d42b922f1a">

Big screen with MasterLayoutConfig.footer.hasLogoOnScroll = false;
This is ok
<img width="378" alt="Screenshot 2024-08-23 at 11 20 11" src="https://github.com/user-attachments/assets/43fe8bfe-c296-40fa-b5df-cf42b9de0b02">

But on smaller screen I get footer logo back. (screen with below 906px)
Not OK
<img width="389" alt="Screenshot 2024-08-23 at 11 22 28" src="https://github.com/user-attachments/assets/44174614-e4d0-4e96-b9aa-b36ddcbb69e9">

### Description

```true
I try to get rid of the Swiss Logo in Footer.

I do it with 
MasterLayoutConfig.footer.hasLogoOnScroll = false;

This works fine for Big Screens. But on a screen below 906px I get the logo back. 

I think the CI doesn't need this footer logo. Is this a bug or how can I avoid having this logo on small screens?
```

### Reproduction

```true
https://stackblitz.com/edit/oblique-master-layout-vjf7pl?file=src%2Fapp%2Fapp.component.ts
```

### Expected behaviour

```true
I would like that the Swiss Logo is not show (on small screens too)
```

**Comment by nina-egger** [comment]
Hello @BenjaminHofstetter 

I will look into this.

Regards
Nina

**Comment by nina-egger** [comment]
Hello again, 

From what I can see the CI/CD demands that a logo is always present and visible. The only way I see to get rid of it is to set

`ObMasterLayoutConfig.footer.custom = true `

and supply your own footer.

**Comment by BenjaminHofstetter** [comment]
Thank you for clarification @nina-egger . Currently I hide it with (in styles.scss)

```css
.ob-footer-item-logo {
    display: none !important;
}
```
