### ISSUE TITLE
Standalone Components & SSR

### ISSUE THREAD

**Issue by robinloeffel** [oblique-bit/oblique#137]
### Description

Are those features planned? Standalone Components are a massive DX improvement, and the Angular team recommends new projects use them. SSR can greatly improve the performance of Oblique-based applications. The latest version of Oblique requires Angular version 17, but doesn't support either of those features. On the public [roadmap](https://oblique.bit.admin.ch/introductions/roadmap) they're not mentioned.

**Comment by nina-egger** [comment]
Hey @robinloeffel 

I apologize for the late answer. Standalone is planned but our schematics are not compatible yet. We would need to completely rewrite them and they are not the highest priority right now. 

About the SSR. From what I know we plan to support it eventually but it is also not the main priority at the moment.

Regards
Nina
