### ISSUE TITLE
The doc is still mentioning to install angular cli 17 and material 17

### ISSUE THREAD

**Issue by BenjaminHofstetter** [oblique-bit/oblique#145]
### Oblique version

12

### Description

```true
I think angular / cli / material 17 is not valid anymore here for Oblique 12. 
https://oblique.bit.admin.ch/introductions/getting-started-as-a-developer
```

### Location

https://oblique.bit.admin.ch/introductions/getting-started-as-a-developer

**Comment by OlivierPerceboisGarve** [comment]
Hi Benjamin,

thanks for the heads up. 
We created the support ticket https://jira.bit.admin.ch/browse/OUI-3360 and the dev ticket https://jira.bit.admin.ch/browse/OUI-3359 to fix this. The fix is now done.

Thanks again
-Olivier

**Comment by BenjaminHofstetter** [comment]
it's fixed
