### ISSUE TITLE
HTTP Interceptor override/disable all notifications

### ISSUE THREAD

**Issue by tolsam** [oblique-bit/oblique#16]
In Oblique's HTTP Interceptor the property `api.notification.active` defines if a notification should be displayed in case of API error response. If that property is set to `false` then no notifications are shown except if the HTTP error code is >= 500.

Is there a way to disable or customize the notifications also in these cases? For example in case of 500 we want to additionally show a transaction id that is returned as header from the server, so that the error can be traced using that id.

**Comment by gillerr** [comment]
The `ObHttpApiInterceptorConfig.api.notification.text` property lets you configure the error message that will be displayed, but doesn't support parameters. Which means it's no use in your use case.

Anyway, in the upcoming 6.0.1 version, the `api.notification.active` property will completely turn notifications off on API calls, even for those above 500.

**Comment by gillerr** [comment]
Released with Oblique 6.0.1
