### ISSUE TITLE
How can locales be added or removed after initialization?

### ISSUE THREAD

**Issue by tolsam** [oblique-bit/oblique#20]
I created a project using Oblique and configured the following three locales (de-CH fr-CH it-CH) from the CLI. Now I want to add a fourth locale (eg. en-CH), but I can't find how the initial three locales are loaded, to add also the new locale "automatically".

I found a way to configured it through the Layout configuration `layoutConfig.locale.locales.push("en-CH")`, but I wanted to understand how the initialization is made and how I could remove a initial locale if needed in the future.

**Comment by gillerr** [comment]
Hello

`de-CH`, `fr-CH` and `it-CH` are the default supported locales of Oblique, meaning it's not necessary to specify them in your project. An alternate locales list is to be provided through the `ObMasterLayoutConfig` service. Should you want to remove one, then you need do overwrite the `locales` array with the locales you want: `layoutConfig.locale.locales = [' de-CH', 'fr-CH'] ;` 

For Oblique up to version 5 the locale management was done by the `ObMasterLayoutService`, this is why it's configurable through the `ObMasterLayoutConfig`. With Oblique 6, this has been extracted to the `ObLanguageService`(https://github.com/oblique-bit/oblique/blob/master/projects/oblique/src/lib/language/language.service.ts). As we're working on Oblique's configuration options, the locales configuration has not been moved.

Does this answer your question?

Cheers
René

**Comment by tolsam** [comment]
Hello,

I just found where the initialization is made `locale: ObILocale = {locales: ['de-CH', 'fr-CH', 'it-CH'],` in _ObMasterLayoutConfig_.  So for everything else, we must add or override the locales array.

Thank you
