### ISSUE TITLE
New styling for readonly fields

### ISSUE THREAD

**Issue by OlivierPerceboisGarve** [oblique-bit/oblique#21]
Hi
we are implementing a new stying for our readonly fields. Ideally and for the sake of consistency, that should be implement at your level.

<img width="785" alt="Screenshot 2021-04-06 at 10 58 50" src="https://user-images.githubusercontent.com/42507/113686106-32362680-96c7-11eb-9fe4-0189e7aac79e.png">

**Comment by gillerr** [comment]
Hi

Thanks for your input, I do agree that each state styling should be provided by Oblique. In fact, we are currently working on the accessibility of disabled form elements. We want them to be clearly identified as disabled while still being readable for everyone. But we need to make sure both `readonly` and `disabled` cases are covered. Actually, out of curiosity, why are you using `readonly` over `disabled`?

If I understand your screenshot correctly, you restyled readonly inputs to look like regular text  with a lighter color. Which means a user might not realize they are actual inputs. Why did you choose to implement it that way? We're still unsure of the best way to display such inputs, so your input is valuable.

Thanks

**Comment by OlivierPerceboisGarve** [comment]
Well in the next stories it seems that some of these fields are becoming editable, based on the context. So I thought it was convenient to just toggle the attribute on the fields. Also it seems that I have to send these readonly values to my backend, even though I need to clarify that spect.

As for the graphic design, the choice has been made by the graphic designers, Sarah Schöni and Philippe Lehmann, I think you talked with them earlier on. Btw they are putting their screens on zeplin.io, I think it would be more convenient if you had access to the designs they are producing.

**Comment by gillerr** [comment]
I clarified the situation with the designers. Actually we do already have a consistent styling for both `readonly ` and  `disabled`  that is accessible. 
We'll integrate it with lots of other design improvements in the upcoming Oblique 7 version.

I don't think I met with either of the designers you mentioned, but it would be interesting to see what they did design.

**Comment by OlivierPerceboisGarve** [comment]
Sorry @gillerr I missed you answer. Our designers are Sarah Schöni and Philippe Lehmann. I believe they can give you access to zepplin
