### ISSUE TITLE
Swiss CI/CD

### ISSUE THREAD

**Issue by BenjaminHofstetter** [oblique-bit/oblique#24]
I am a bit confused about "Enforcement of the Swiss CI/CD".

There is the Swiss style guide (https://github.com/swiss/styleguide) and here is Oblique. For our Project Oblique fits much better because we are using Angular. But is the CI/CD of Oblique accepted as "Swiss CI/CD" or do we have to adapt it more to "https://github.com/swiss/styleguide"?

**Comment by gillerr** [comment]
Hello

The Swiss style guide have been build for websites. This is the reason the BIT developed Oblique, meant for web applications. Oblique enforces the CI/CD with some adaptations that makes sense for applications (for instance, we use the full width of the screen). As all the mandatory elements of the CI/CD are left untouched, Oblique is CI/CD conform. The federal Chancellery supports Oblique.

A note on Frutiger. To be really CI/CD conform, a web application have to use Frutiger, this is why it's the default font in Oblique. Unfortunately, the license of Frutiger doesn't allow us to deliver the font files with Oblique, you will have to download them separately. The process is described on Oblique's doc front page: https://oblique.bit.admin.ch/oblique.

Does this answer your question?

**Comment by BenjaminHofstetter** [comment]
Yes it does. Thank you for Oblique. It helps us a lot.
