### ISSUE TITLE
Execute code before navigating via main navigation

### ISSUE THREAD

**Issue by KKostis** [oblique-bit/oblique#29]
Hello,

I am using the main navigation to navigate to various urls. For a specific case however, I want to change certain variables before the navigation takes place. I have tried several ways to achieve that, but have been unsuccessful. I even tried to add a 'click' event listener to the link in question by assigning an id to it, but the click event gets triggered after the navigation. Is there a way to execute code by clicking on the main navigation link, before the actual navigation takes place?

**Comment by gillerr** [comment]
Hello

Oblique don't expose an Output for that purpose. It seems to be a very specific use case, so I don't think we'll implement it.  Have you tried with a `mousedown` event? It should be triggered before the navigation.

Another, cleaner, option would be to listen to the `NavigationStart`  event:

	constructor(router: Router) {
		router.events.pipe(
			filter(event => event instanceof NavigationStart),
			filter(event => event url === 'some url') // in case the code should be applied only on targeted routes
		).subscribe(() => {
			// This code should be executed before the navigation occurs
		});
	}

**Comment by bmnnnkls** [comment]
a canActivate guard on the route might be another option https://angular.io/api/router/CanActivate. you can return a new UrlTree to redirect

**Comment by KKostis** [comment]
The `mousedown` event occurred to me as well. There is however the case, where the user can move the mouse outside the tab before releasing the mouse button, which would execute the corresponding code but not the navigation. The same goes for the `mouseup` event.

Regarding the NavigationStart and the canActivate guard solutions, I decided to go with the second option, since it is more "targeted". The NavigationStart would work just fine, but it would get triggered on every navigation event, which is redundant in my case. 

Thank you very much for your help! I will close the issue.
