### ISSUE TITLE
Documentation Layout Compose has Loading Problem

### ISSUE THREAD

**Issue by matthiasbaldi** [oblique-bit/oblique#3]
I have seen that the layout-composer on the docs site https://oblique.bit.admin.ch/layout-composer has a loading problem (`Blocked a frame with origin "https://oblique.bit.admin.ch" from accessing a cross-origin frame.`).

May an easy fix on the server side configuration.

![image](https://user-images.githubusercontent.com/12791996/78218836-ba835980-74be-11ea-8a39-7099a39b8786.png)

**Comment by gillerr** [comment]
Thank you for reporting this. Actually it works from inside of the Confederation Network  but CORS policy blocks it form the outside.

**Comment by gillerr** [comment]
I finally found & fixed the problem (WAF security), @matthiasbaldi could you confirm that it works now.

**Comment by matthiasbaldi** [comment]
> I finally found & fixed the problem (WAF security), @matthiasbaldi could you confirm that it works now.

Ya works. Thank you.
