### ISSUE TITLE
Vertical scroll for navigation menu on small resolution screen. 

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#32]
It seems that the navigation menu in mobile view isn't scrollable if it's too big vertically. 

How to reproduce:
* Go on: https://oblique.bit.admin.ch/oblique
* Increase page size `ctrl+shift+plus` to maximum
* Click on the hamburger button
* Cannot access to last navigation elements

![image](https://user-images.githubusercontent.com/3356843/126173314-5f2ea513-bb7f-4907-95dc-163aec717f81.png)

**Comment by gillerr** [comment]
Thank you for the bug report, we'll look into the issue.

**Comment by nina-egger** [comment]
Scrolling works again in Oblique 11. 
Closing this issue.
