### ISSUE TITLE
Deprecation warning, details below:

### ISSUE THREAD

**Issue by webia1** [oblique-bit/oblique#33]
Source File: 

https://github.com/oblique-bit/oblique/blob/5feb5d89b6195c8dd7c234f223039b362f250a4f/projects/oblique/src/lib/master-layout/master-layout-navigation/master-layout-navigation.component.ts#L134

[>> Deprecation Warning (Angular Official Documentation)](https://angular.io/api/router/Router#isActive)

Line: ~_isActive(url: string | UrlTree, exact: boolean): boolean_~

A possible up-to-date Implementation Example (using [*isActiveMatchOptions*](https://angular.io/api/router/IsActiveMatchOptions)):

```js
  markActiveLink() {
    this.router.events
      .pipe(
        takeUntil(this.unsubscribe),
        filter((evt) => evt instanceof NavigationEnd)
      )
      .subscribe(
        () =>
          (this.links = this.links.map((link) =>
            Object.assign(Object.assign({}, link), {
              active: this.router.isActive(link.url, {
                paths: 'subset',
                fragment: 'ignored',
                queryParams: 'ignored',
                matrixParams: 'ignored',
              }),
            })
          ))
      );
```

**Comment by gillerr** [comment]
Thanks for the report but the source code you provided does use `isActiveMatchOptions`. Actually both `link.routerLinkActiveOptions` and `this.routerLinkActiveOptions` are of type `IsActiveMatchOptions` . So I don't understand how you managed to trigger this Deprecation Warning.

IntelliJ doesn't complain, which IDE are you using?

**Comment by webia1** [comment]
you're welcome, thank you, the provided code is just an example, I'll give you the detailed error message in the browser at the next opportunity,..

**Comment by webia1** [comment]
the second param of `router.isActive` may not be a boolean anymore; the following is deprecated:

isActive(url: string | UrlTree, `exact: boolean`): boolean

Please see the attached video; thank you very much,..


https://user-images.githubusercontent.com/2741558/126446824-f29560b9-f04e-4ade-90a1-fa41c3e4bf7f.mp4

**Comment by webia1** [comment]
FYI, the error above is not oblique relevant; I've just recognized that the second parameter is deprecated while I was debugging,..

**Comment by gillerr** [comment]
Ok, in your first post, you referenced a line of code where the problem has already been taken care of. Therefore I thought you got this warning with Oblique 7.
But then, In the video, it is clearly the old code, e.g. before Obliuqe 7-RC.2.

The code has already been refactored to remove this warning:
https://github.com/oblique-bit/oblique/commit/8a4ea151de49cca89f0f3521f27a2baa743501bc#diff-bc8246a4bb29e20b8a52e6215ab3bec70218fa40aa55e4291f01c18962b3cea7
