### ISSUE TITLE
Javascript is required / Unsupported browser warning in additional languages

### ISSUE THREAD

**Issue by meszaroszoltan** [oblique-bit/oblique#35]
Currently the [_Javascript is required_ / _Unsupported browser_ warning](https://github.com/oblique-bit/oblique/blob/master/src/index.html) is displayed only in English.
I think it would be a good idea to add the warnings in other official Swiss languages too.

**Comment by c-saner** [comment]
Hello, Thank you for your input. We'll look into your request.

**Comment by gillerr** [comment]
This has been released with Oblique 8.
