### ISSUE TITLE
Update oblique schematics problem in html files

### ISSUE THREAD

**Issue by mgiannelli** [oblique-bit/oblique#4]
**I'm submitting a  bug report**

**Environment:**
* **Angular version:** 9.0.4
* **Oblique version:** 5.0.4

**Bug description**

When I do a ng-update in oblique 5.0.4, schematics update all files correctly, but there is a problem in .html files.
In fact, schematics modify every string with begin 'or' in 'ob' in .html files.

**Example**

I have an @Input was name [organization] and schematic change it in [obganization], but not in .ts files. 
The same case with a variable in html file was named original before update and changed it in obiginal,  but not in .ts files. 
Schematics also modify html comments (a little less serious).

Thanks in advance.

**Comment by gillerr** [comment]
Thank you for the report. This is actually a known problem and will be improved in the upcoming 5.1.0 release
