### ISSUE TITLE
Padding on <main> isn't working as expected on firefox

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#40]
Hello, if you go the main page of oblique, you can see there is more space on chrome than firefox.
![image](https://user-images.githubusercontent.com/3356843/130741163-c306f184-af6c-4d78-8095-65e19d71c4c1.png)
![image](https://user-images.githubusercontent.com/3356843/130741114-25e92af8-b58b-4da4-a7ac-e20100f43b91.png)

It looks like nothing but the implication can be quite ugly in our website 
![image](https://user-images.githubusercontent.com/3356843/130741623-96c2fb99-360a-476b-891c-fe4b6cf6ed99.png)
![image](https://user-images.githubusercontent.com/3356843/130741523-e7c9794a-546c-48ac-9fd6-32bb3354ccd2.png)

Weirdly enough when the width is smaller, then it works on firefox too:
![image](https://user-images.githubusercontent.com/3356843/130742132-d232df5d-0c74-44c2-8dec-5c6943d54c6a.png)

**Comment by gillerr** [comment]
Sorry for the answer delay, We had quite some things to take care of.

This seem to be a firefox bug

The following snippet can serve as a workaround until we fix it.
```
.ob-main-layout::after {
    content: "";
    height: 16px;
    display: block;
}
```

**Comment by ice-blaze** [comment]
Sorry for the late answer. Thank you very much.
