### ISSUE TITLE
ObMandatoryDirective generates constant stream of control value changes

### ISSUE THREAD

**Issue by ufleisch** [oblique-bit/oblique#45]
With Oblique 7, the new module `ObMandatoryModule` instruments form controls with a validator but without `required` attribute with a `ngAfterContentChecked` hook, which generates a constant stream of events generated by `updateValueAndValidity()`.

We have a project which does no longer work after the migration to Oblique 7 because it uses several custom validators and `valueChanges` handlers on controls. For example, when a location is set in a form, its `valueChanges` handler sets latitude and longitude in other controls. Now this handler is constantly called thereby overwriting the values. Other controls are affected as well, it is no longer possible to enter any values into the controls. As a workaround, we no longer import the whole `ObliqueModule` but only the effectively used sub modules, so that `ObMandatoryModule` is not active.

This behavior could be improved. The `updateValueAndValidity()` could only be triggered and `this.formFieldControl.required` could only be set when its value has really changed.

Additionally, in `selector: 'input:not([required]), mat-select:not([required),`... a closing `]` seems to be missing.

**Comment by c-saner** [comment]
Hello,

Thank you for your input.

We'll look into your improvement suggestion.

Kind regards

**Comment by gillerr** [comment]
According to https://github.com/angular/components/issues/2574, the goal of the ObMandatoryModule is now covered directly by Angular. If this is really the case, then we'll remove the feature altogether.

**Comment by gillerr** [comment]
The `ObMandatoryModule` will be removed with Oblique 8 as Angular 13 takes care of that.

**Comment by gillerr** [comment]
The `ObMandatoryModule` has been removed with Oblique 8
