### ISSUE TITLE
Ob-Accessible link leads to "unknown-route"

### ISSUE THREAD

**Issue by zuercheram** [oblique-bit/oblique#48]
We are developing an Angular application using Oblique.
At some point, when tabbing through our app, the Ob-Accessible pops up and gives us the possibility to navigate to the main content or the main page. Now, we have an issue with the hyperlink to navigate to the main content.
![accessible](https://user-images.githubusercontent.com/26512108/146196803-eac924d6-ff1a-486c-bca2-69cdcca9de0d.PNG)
 
When I navigate to the main content link, the router redirects us to "unknown-route", although the  route is correct.

The link displayed in the browser target URL label looks like the following screenshot shows:
![Url-behind-link](https://user-images.githubusercontent.com/26512108/146197137-ee4a6eec-68cf-4c1c-8725-f59b48574f91.png)

Since, we have not configured any links in the Ob-Accessible, We assume, that Oblique takes the URL path, appends "#content" and uses that as router link. The original URL in the browser looks like the following:
![original-url](https://user-images.githubusercontent.com/26512108/146197512-a8eebdd3-1b27-48a2-808a-38cb2279792b.png)

The router tracing output shows, that the router received the following URL: 
![router-traceing-output](https://user-images.githubusercontent.com/26512108/146198427-9ae88f2a-6648-4e48-ade3-8172f08cf7cf.PNG)

The router got the URL: /map%3Fbasemap%3D%2522black-white%2522#content, which it does not recognize as one of the configured routes and lead to "unknown-route" fallback route.

Our Route configuration looks like this:
![route-config](https://user-images.githubusercontent.com/26512108/146204606-42e99646-8aa3-442b-8da3-30d5cbb46ee9.PNG)

Thanks for having a look into the problem.

**Comment by c-saner** [comment]
Hello @zuercheram,

Thank you for your input.

We'll look into the issue.

Kind regards.

**Comment by gillerr** [comment]
This has been fixed with Oblique 7.0.2. @zuercheram on which version did you experience this bug?
