### ISSUE TITLE
module not found warning at build

### ISSUE THREAD

**Issue by rosenbee** [oblique-bit/oblique#51]
Hi, when I'm building my project with Oblique 7.1.2 I get the following warning in the console:

```
** Angular Live Development Server is listening on localdev.com:4200, open your browser on http://localdev.com:4200/ **


✔ Compiled successfully.
✔ Browser application bundle generation complete.

6 unchanged chunks

Build at: 2022-01-26T15:02:00.630Z - Hash: 0696e117b4017984d850 - Time: 10777ms

./node_modules/@oblique/oblique/fesm2015/oblique.js:2204:13-36 - Warning: Module not found: Error: Can't resolve 'package.json' in '/Users/u80852337/angular/sia/node_modules/@oblique/oblique/fesm2015'

./node_modules/@oblique/oblique/fesm2015/oblique.js:2218:13-82 - Warning: Module not found: Error: Can't resolve 'package-lock.json' in '/Users/u80852337/angular/sia/node_modules/@oblique/oblique/fesm2015'



✔ Compiled successfully.
```
Is this something I should be concerned of, and if yes, do you know what I should do? Thanks a lot.

**Comment by gillerr** [comment]
Hi, thanks for your report.

Theses warning should not concern you, They mean the telemetry data (https://oblique.bit.admin.ch/components/telemetry?theme=material) could not be collected, but this has zero impact on your project.

To help me understand what happened, can you please tell me about your project configuration?
- which Angular version
- which Node / NPM version
- is your project located in `src` or in `projects/sia` folder?
- do you have a monorepo with multiple projects in the same git repository?
- are you using additional tooling like NX or Lerna?

Thank you for your help

**Comment by nina-egger** [comment]
no feedback received. closing issue
