### ISSUE TITLE
Datepicker arrow on top right issue.

### ISSUE THREAD

**Issue by webia1** [oblique-bit/oblique#54]
Dear all, 

Chrome v99+ has some problems with the date picker. An image illustrating the concern is visible in the appendix.

FYI, kind rgds

<img width="600" alt="Screenshot 2022-03-14 at 11 03 10" src="https://user-images.githubusercontent.com/2741558/158150345-b7884d8c-13d2-4fe6-834f-a0eb860aecb0.png">

**Comment by gillerr** [comment]
Thanks for the report.
This bug is already fixed on the develop branch and will be part of the next release.

**Comment by gillerr** [comment]
Fixed with Oblique 8.1.0
