### ISSUE TITLE
Main navigation: The "Guidelines" navigation item is not expanding when pressing it after the "Roadmap" item

### ISSUE THREAD

**Issue by znuteri** [oblique-bit/oblique#56]
Navigation Items at the main navigation that contain sublists do not expand if the user activates them one after an other .
How to reprodude:
1. Press Roadmap
2. Press Guidelines
The Guidelines item is not expanding. The user has to press this item multiple times to expand it.

**Comment by gillerr** [comment]
Thank you for your report.
This problem is already known to us and we're working on a solution.

**Comment by gillerr** [comment]
This has been fixed with Oblique 8.1.0
