### ISSUE TITLE
Cannot find module '@oblique/oblique' with Angular13 and Jest

### ISSUE THREAD

**Issue by Flyingdot** [oblique-bit/oblique#64]
It seems like there's a problem when running tests with Angular13 and Jest, probably with the module resolution of Jest. I was able to isolate and reproduce the problem with a clean setup.

There is some information in the jest-preset-angular docs (https://thymikee.github.io/jest-preset-angular/docs/guides/angular-13+), but it did not fix my issue (or I was not able to).

## Reproduce

1.`ng new my-app`
2. `ng add @oblique/oblique`
3. In app.component.spec.ts, add import to `ObMasterLayoutModule` to fix error when running tests (NG0304: 'ob-master-layout' is not a known element) and add it to TestBed-Imports too (see code below)
4. Running tests now fails with "Cannot find module '@oblique/oblique'"

I also tried to mock the module (and the TranslatePipe) away with ng-mocks, but it still fails with the same error on the import itself.

### app.component.spec.ts
```typescript
import {TestBed} from '@angular/core/testing';
import {RouterTestingModule} from '@angular/router/testing';
import {AppComponent} from './app.component';
import {ObMasterLayoutModule} from '@oblique/oblique';
import {TranslatePipe} from '@ngx-translate/core';

describe('AppComponent', () => {
	beforeEach(async () => {
		await TestBed.configureTestingModule({
			imports: [RouterTestingModule, ObMasterLayoutModule],
			declarations: [AppComponent, TranslatePipe]
		}).compileComponents();
	});

	it('should create the app', () => {
		const fixture = TestBed.createComponent(AppComponent);
		const app = fixture.componentInstance;
		expect(app).toBeTruthy();
	});

	it(`should have as title 'my'`, () => {
		const fixture = TestBed.createComponent(AppComponent);
		const app = fixture.componentInstance;
		expect(app.title).toEqual('my');
	});

	it('should render title', () => {
		const fixture = TestBed.createComponent(AppComponent);
		fixture.detectChanges();
		const compiled = fixture.nativeElement as HTMLElement;
		expect(compiled.querySelector('.content span')?.textContent).toContain('my app is running!');
	});
});

```

## Error:
```
Cannot find module '@oblique/oblique' from 'src/app/app.component.spec.ts'

      2 | import {RouterTestingModule} from '@angular/router/testing';
      3 | import {AppComponent} from './app.component';
    > 4 | import {ObMasterLayoutModule} from '@oblique/oblique';
        | ^
      5 | import {TranslatePipe} from '@ngx-translate/core';
      6 |
      7 | describe('AppComponent', () => {

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/app/app.component.spec.ts:4:1)
```

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is your ticket number on our system: OUI-1747

Kind regards

**Comment by Flyingdot** [comment]
Thanks.

By downgrading some packages, I was able to work around the issue:
- jest@27
- jest-preset-angular@11

**Comment by c-saner** [comment]
Hello, 

We are glad that the tests are now working in your project 😃 

Effectively the latest version of Oblique support only Jest 27 and jest-preset-angular 11.

Other input: instead of importing the `ObMasterLayoutModule` you should import the `ObliqueTestingModule`.

Kind regards
