### ISSUE TITLE
ng test fails

### ISSUE THREAD

**Issue by laz4triumph** [oblique-bit/oblique#66]
Hello,
I have updated to the v.13 of angular and materials , and also to the version 8.1 of oblique.
When I run the cmd ng test I receive this error:

_An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID_

[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (D:\Software\SIS\SIS-HABE-UI\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)

I have tried to fgure out what was wrong but I really don't understamd.

Here my package.json

{
  "name": "sis-habe-ui",
  "version": "0.0.0",
  "scripts": {
    "start": "ng serve",
    "start-secure": "ng serve --ssl --ssl-cert ssl/certificate.pem --ssl-key ssl/privkey.pem --port 4201",
    "build": "ng build",
    "build-prod": "ng build --configuration production --aot --build-optimizer",
    "test": "ng test",
    "e2e": "ng e2e",
    "lint": "ng lint",
    "format": "npm run lint -- --fix"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.3.11",
    "@angular/cdk": "^13.3.9",
    "@angular/common": "~13.3.11",
    "@angular/compiler": "~13.3.11",
    "@angular/core": "~13.3.11",
    "@angular/forms": "~13.3.11",
    "@angular/localize": "13.3.11",
    "@angular/material": "^13.3.9",
    "@angular/platform-browser": "~13.3.11",
    "@angular/platform-browser-dynamic": "~13.3.11",
    "@angular/router": "~13.3.11",
    "@bfs-sis/habe-web-api-client": "^0.2.0--51576-updateobl0001.649.73649",
    "@ngx-translate/core": "^14.0.0",
    "@oblique/oblique": "^8.1.1",
    "@popperjs/core": "^2.5.3",
    "angular-oauth2-oidc": "^13.0.1",
    "file-saver": "^2.0.5",
    "jwt-decode": "^3.1.2",
    "rxjs": "^7.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-builders/jest": "^11.0.0",
    "@angular-devkit/build-angular": "~13.3.8",
    "@angular-eslint/builder": "13.5.0",
    "@angular-eslint/eslint-plugin": "13.5.0",
    "@angular-eslint/eslint-plugin-template": "13.5.0",
    "@angular-eslint/schematics": "13.5.0",
    "@angular-eslint/template-parser": "13.5.0",
    "@angular/cli": "~13.3.8",
    "@angular/compiler-cli": "~13.3.11",
    "@types/jasmine": "~3.6.0",
    "@types/jest": "^26.0.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "5.27.1",
    "@typescript-eslint/parser": "5.27.1",
    "ajv": "^6.0.0",
    "eslint": "^8.17.0",
    "eslint-config-prettier": "^8.0.0",
    "eslint-plugin-prettier": "^4.0.0",
    "husky": "^4.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jest": "^26.0.0",
    "jest-sonar-reporter": "2.0.0",
    "prettier": "^2.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.6.4"
  },
  "jestSonar": {
    "reportPath": "./coverage/sonarQube",
    "reportFile": "sqr.xml",
    "indent": 4,
    "sonar56x": true
  },
  "husky": {
    "hooks": {
      "pre-push": "npm run format"
    }
  }
}

Thank you

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is your ticket number on our system: OUI-1796.

Kind regards

**Comment by c-saner** [comment]
Hello,

This issue appears when not all the dependencies have been updated to a version compatible with Angular 13 and Oblique 8.1.

Updating the following dependencies should fix the issue:

- ajv
- @angular-builders/jest
- @types/jest
- jest

But we recommend to go though all your dependencies.

Kind regards
