### ISSUE TITLE
mat-datepicker icon misplaced

### ISSUE THREAD

**Issue by BenjaminHofstetter** [oblique-bit/oblique#68]
I tried oblique 9 and almost all looks good except the date-picker icon inside and input is misplaced. 
<img width="330" alt="Screenshot 2022-07-19 at 11 57 08" src="https://user-images.githubusercontent.com/8033981/179726589-9b155e74-25df-47bc-8a5b-6a00beea0033.png">

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-1818.

Kind regards

**Comment by c-saner** [comment]
This has been fixed with the version 9.0.2.
