### ISSUE TITLE
External url redirection page (feature questions)

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#69]
Hello Oblique team,

I saw on some website a page before you are redirecting outside the website. 

- Is it a good practice? 
- Do you think it should be in the future in Oblique? 

I saw you have https://oblique.bit.admin.ch/components/external-link?theme=material but I think it doesn't answer my question.

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into your question. Here is the ticket number on our internal system: OUI-1827.

Kind regards
