### ISSUE TITLE
Oblique's website title bug.

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#70]
Hello Oblique team,

When you are browsing on Oblique's website your can at any moment search for the component with the search bar top right. But if you do instead of being redirected to the UI Components tab you see that I stay on my current tab but with the content of the UI components tab.

In the screenshot I was on testing, then search a component and click on it.

Cheers

![image](https://user-images.githubusercontent.com/3356843/180262214-b29f24e0-db11-476a-8de2-b040957dfe09.png)

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-1828.

Kind regards

**Comment by c-saner** [comment]
Hello,

It looks like this issue doesn't affect Oblique but the documentation.

As the documentation is an other project and isn't tracked here on GitHub, I'll close this issue and create a new ticket in our internal system.

Kind regards
