### ISSUE TITLE
Website oblique documentation column close button doesn't follow.

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#71]
Hello Oblique team!

If you go on this page https://oblique.bit.admin.ch/components/icon?theme=material and scroll down, you see at start that the small button to close the left pane is follow at the start, then disappearing, then it appears again once you scroll down all the page. I don't know if it is expected behaviour or if the reduce button should be always visible which ever the scroll position is.

Another bug on the icon documentation is the bootstrap mode. All icons seems to be cropped.

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-1883.

Kind regards

**Comment by c-saner** [comment]
The issue has been fixed. Thanks a lot for your report :)
