### ISSUE TITLE
Oblique's website: Button documentation

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#72]
Hello Oblique team!

On the button documentation https://oblique.bit.admin.ch/components/button?theme=material, if you select secondary, then you press on the text toggle to remove it. The icon button get's primary color back (should stay secondary)
![image](https://user-images.githubusercontent.com/3356843/180998298-c9c85534-cbef-4160-9ecd-5dd654bd5c3a.png)
![image](https://user-images.githubusercontent.com/3356843/180998346-640514a9-37b2-41a3-8256-99e8da167753.png)

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

As the documentation is an other project and isn't tracked here on GitHub, I'll close this issue and create a new ticket in our internal system.

Kind regards
