### ISSUE TITLE
Oblique documentation still make reference to ObliqueTestingModule

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#74]
Since ObliqueTestingModule is deprecated I think on this page https://oblique.bit.admin.ch/training the line `Use the ObliqueTestingModule in the unit tests of their projects` is outdated.

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

As the documentation is an other project and isn't tracked here on GitHub, I'll close this issue and create a new ticket in our internal system.

Kind regards
