### ISSUE TITLE
Inconsistency of translation documentation

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#75]
The documentation https://oblique.bit.admin.ch/guidelines/coding recommend not to use `i18n` but you see in the examples above that they contain `i18n`. 
![image](https://user-images.githubusercontent.com/3356843/183381048-3e752b05-f3a1-4739-ab0c-b838534f83ba.png)

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

As the documentation is an other project and isn't tracked here on GitHub, I'll close this issue and create a new ticket in our internal system.

Kind regards
