### ISSUE TITLE
Documentation navigation very long make scroll position broken.

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#77]
If you go on this documentation https://oblique.bit.admin.ch/components/tooltip?theme=material which is quite at the end of the page, the scroll position is also at the end and you have to scroll up to see the real content of the tooltip documentation. 

One possible solution is to have a scroll on the navigation tree too (like bootstrap documentation https://getbootstrap.com/docs/5.2/migration/)

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

As the documentation is an other project and isn't tracked here on GitHub, I'll close this issue and create a new ticket in our internal system.

Kind regards
