### ISSUE TITLE
Master layout  navigation on small screens

### ISSUE THREAD

**Issue by BenjaminHofstetter** [oblique-bit/oblique#79]
The navigation on small screen is feels inconsistent. 

When i click on top level items like Oblique, Ui Components...
<img width="593" alt="Screenshot 2022-09-10 at 22 15 07" src="https://user-images.githubusercontent.com/8033981/189500384-29a0477e-b110-4a8b-8d1f-511e3e603ced.png">

... nothing happens. I have to close the menu manually (click on the X) to see the new page (e.g. Ui Components). 

When i click on something with a submenu then the behaviour is different. When i choose the top level item "Roadmap" then i see the submenu below. 

<img width="588" alt="Screenshot 2022-09-10 at 22 20 45" src="https://user-images.githubusercontent.com/8033981/189500527-b292b5f3-3d1f-4e98-9391-aa78c84f7bbe.png">

In that menu when i click Roadmap. Then the menu closes its self and i see the new page.

**Comment by c-saner** [comment]
Hello,

Thank you for your report, we'll look into this issue.

Kind regards

**Comment by c-saner** [comment]
Here is the ticket number on our internal system: OUI-1948

**Comment by punix81** [comment]
This has been fixed with the version 9.2.3
