### ISSUE TITLE
Header overflow issue

### ISSUE THREAD

**Issue by bmnnnkls** [oblique-bit/oblique#8]
On our projects i had to overwrite `overflow: hidden` on the oblique header. It causes the header widget drop-downs to be cut off. You can observe the same behaviour on https://oblique.bit.admin.ch/oblique, if you search something in the header-search, the results are not visible either.

**Comment by gillerr** [comment]
Yes, this bug has been introduced by the new banner feature. It's fix will be included in the next Oblique release. 
Simply overriding the `overflow` property will cause the banner to overflow with the small header.
