### ISSUE TITLE
Telemetry silent console log

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#80]
Hello Oblique team,

I updated my project from oblique 8 to 9 and now I have a lot of tests with console.log(), is there a way to disable it inside oblique? 
![image](https://user-images.githubusercontent.com/3356843/193040499-5074fff5-dd98-48aa-8169-671bc2dc8ed3.png)

Thank you for your help.

**Comment by c-saner** [comment]
Hello,

Thank you for your report, we'll look into this issue.

Kind regards

**Comment by c-saner** [comment]
Hello,

There are at the moment two options if you wish to disable those logs:

1. Activate the telemetry
2. Writing a mock implementation of console.info for jest like we did here: https://github.com/oblique-bit/oblique/blob/master/tests/setupJest.ts

If you need support to activate the telemetry or writing the mock implementation of console.info, please contact us at Oblique@bit.admin.ch.

Kind regards

**Comment by ice-blaze** [comment]
Ok thank you very much. I have another mock which limits only messages that I don't want to see, because maybe there could be other `console.info` that could be helpful. I share it here in case someone else might have the use for it.

```typescript
export function muteConsoleInfo(): void {
  jest.spyOn(console, 'info').mockImplementation((message) => {
    const messagesToIgnore = ['Oblique Telemetry is disabled.'];

    if (messagesToIgnore.includes(message) === false) {
      // eslint-disable-next-line no-console
      console.log('INFO: ' + message);
    }
  });
}
```
