### ISSUE TITLE
ObDropZone doesn't trigger event when selecting the same files repeatedly

### ISSUE THREAD

**Issue by Anamon** [oblique-bit/oblique#81]
### Steps to reproduce
- Choose file(s) for upload in the `ObDropZoneComponent`
- Choose the same file(s) for upload in the `ObDropZoneComponent` a second time

### Expected result
The `uploadEvent` output should trigger an event of type `ObEUploadEventType.CHOSEN` both times, containing the same value for the `files` property.

### Actual result
- The event is only triggered the first time.
- Events are triggered again if a different file, or set of files, is selected for upload.
- When then selecting the first file(s) again, the event is also properly emitted.

---

We are handling uploads in custom code, so I don't know if the behaviour is the same if `ObFileUpload` is used to take care of the uploading.

**Comment by c-saner** [comment]
Hello, 

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-2026.

Kind regards

**Comment by c-saner** [comment]
The issue has been fixed with the version 9.3.1 of Oblique.

Thank you for your report 😃
