### ISSUE TITLE
Clear directive hasn't translation in the oblique-en.json file.

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#82]
Hello Oblique team,

When I'm using the directive to clear form inputs the screen reader can't read the translation `i18n.common.clear`. I find out that it's working on the documentation https://oblique.bit.admin.ch/components/form?theme=material#form-control-text-clear but because you have two translation files. The "default" oblique `oblique-en.json` and another one called `en.json`. 

I believe that the key `i18n.common.clear` should be in the `oblique-en.json` file.

(btw I have no idea how the screen reader can access to those translation keys because when I inspect the button I see nothing that looks like a translation)

**Comment by c-saner** [comment]
Hello,

Thank you for your report.

We'll look into this issue. Here is the ticket number on our internal system: OUI-2087

Kind regards

**Comment by gillerr** [comment]
Hi

`oblique-en.json` contains the translations of Oblique itself, `en.json` contains the translations of the project, in this case ObliqueDocs which is a separate project. In ObliqueDocs, the input clear directive is used together with this piece of code `<span class="sr-only">{{ "i18n.common.clear" | translate }}</span>``  that actually provides an accessible text for the button. As this text comes from the project, not Oblique, it is the project's responsibility to translate it.

That being said, I agree that `i18n.common.clear` should be provided by Oblique.

**Comment by gillerr** [comment]
Fixed with Oblique 10.0.0
