### ISSUE TITLE
External link icon changes size depending on the number of line

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#89]
Hello Oblique team,

I rellized that the icon from external link can change size depending on the number of lines in the link. Here an image example: 
![image](https://user-images.githubusercontent.com/3356843/211602985-6e022d21-60d1-437b-9c94-8984ccb1d47d.png)

**Comment by gillerr** [comment]
Hi @ice-blaze 

Thanks for the report, it will be fixed in the next version
