### ISSUE TITLE
Initial Setup not able to launch

### ISSUE THREAD

**Issue by efkah** [oblique-bit/oblique#91]
`app.routing.module.ts` is missing a `,` in line 5
```js
const routes: Routes = [{path: '', redirectTo: 'home', pathMatch: 'full'}{path: 'home', component: HomeComponent}];
```
should be
```js
const routes: Routes = [
	{path: '', redirectTo: 'home', pathMatch: 'full'},
	{path: 'home', component: HomeComponent}
];
```

Also you're leaving `"start": "ng serve"` untouched, you should add switch `--proxy-config proxy.conf.json` here when i chose to add a dev-proxy (step 14)

Minor Issues:
In `package.json` i expected prettier and eslint commands. Is it weird that a freshly generated oblique app throws linting errors?

In `tsconfig.json` i expected typeroots

```json
"typeRoots": [
	"node_modules/@angular/material"
]
```

Also the tests are not working after setup

**Comment by gillerr** [comment]
Hi @efkah 

Thank you for your feedback.  Next time you submit a ticket, could you submit one ticket per issue? Because solving 5 issues in the same ticket will be cumbersome.

I'll have a look at those issues as soon as possible and will come back to you.

**Comment by nina-egger** [comment]
- First issue (app routes) has been fixed (works in 11)

**Comment by nina-egger** [comment]
- proxy config: I will add a feature request (for the ng-add schematics) for that one

**Comment by nina-egger** [comment]
@efkah could you elaborate why you were expecting typeRoots to be added?

"typeRoots": [
	"node_modules/@angular/material"
]

**Comment by efkah** [comment]
sorry I am not working for BIT anymore, if consulting is required u can hire me via the usual contractors

**Comment by nina-egger** [comment]
@gillerr do we close this or keep it open?

**Comment by nina-egger** [comment]
will close the issue then
