### ISSUE TITLE
Usage of '~' in imports is deprecated.

### ISSUE THREAD

**Issue by webia1** [oblique-bit/oblique#94]
Dear Oblique-Team, 

to fix this deprecation warning, you could insert ` "./node_modules"` into `"includePaths"`  in your project configuration (`targets.build.options.stylePreprocessorOptions`) like:

```json
        "stylePreprocessorOptions": {
          "includePaths": [
            "./node_modules"
          ]
        },
```

and remove all `~` from all your SCSS-Files.

FYI, kind rgds

**Comment by gillerr** [comment]
Hi @webia1 

Thanks for your suggestion.

All `~` have been removed with Oblique 10.

Actually it was only used to import bootstrap stylesheets and as bootstrap was already deprecated we didn't bother to solve this warning.
