### ISSUE TITLE
ObButtonModule uses deprecated module

### ISSUE THREAD

**Issue by mischahaenen** [oblique-bit/oblique#96]
ObButtonModule uses MatLegacyButtonModule instead of MatButtonModule. Further Question: Why do I have to import the Material Button Module in the first place?
Oblique Version: 10.0.0

**Comment by gillerr** [comment]
Hi Mischa

The `ObButtonModule` is an extension of the `MatButtonModule`, and both modules do work together and thus both are necessary. This will most probably be improved in the future thanks to directive composition.

Angular Material 15 introduced a huge breaking change that have a massive impact on Oblique's stylesheets. Basically they are to be rewritten. But we're currently working on the integration of the new WebGuidelines, which implies a rewrite of those stylesheets anyway. As we don't have the capacity to rewrite those files twice, we decided to use the Legacy modules for Oblique 10.

The Legacy modules are expected to be dropped in future Oblique versions.

does this answer you questions?

**Comment by bmnnnkls** [comment]
so for angular applications using oblique, the suggested migration path is to stay with legacy material modules until angular material 16 + oblique 11 are ready?

maybe there should be some official statement on the oblique homepage regarding legacy material modules

**Comment by ice-blaze** [comment]
Not most visible but still it was written 
![image](https://user-images.githubusercontent.com/3356843/225347751-5df0613e-1cd6-4920-842e-b74d6f9db2d5.png)

**Comment by gillerr** [comment]
@bmnnnkls 

Yes, you have to stay with Legacy Modules until we finish the migration to the new Webguidelines witch should be ready with Oblique 11.

This information is wildly  available on ObliqueDocs. You can find it on

- home page (https://oblique.bit.admin.ch/home.html):
![Capture](https://user-images.githubusercontent.com/4614502/225875080-b293f155-23d4-4c09-b5b7-60ad1e8d8d99.PNG)

- migration page (https://oblique.bit.admin.ch/getting-started/update-oblique):
![Capture](https://user-images.githubusercontent.com/4614502/225875574-a6e73313-d6ab-4ce1-87ff-91c13e8f4625.PNG)

- getting started page (https://oblique.bit.admin.ch/getting-started/add-oblique):
![Capture](https://user-images.githubusercontent.com/4614502/225875903-fc4cf776-d12b-45ca-94b2-c8fa4551601a.PNG)

- roadmap (https://oblique.bit.admin.ch/roadmap/roadmap):
![Capture](https://user-images.githubusercontent.com/4614502/225876454-52a7ea14-3693-474d-aa11-b301ef739ea8.PNG)

- Changelog (https://oblique.bit.admin.ch/changelog):
![Capture](https://user-images.githubusercontent.com/4614502/225876807-2a0edcea-7284-471d-89dd-79ee2b0fe46d.PNG)
