### ISSUE TITLE
Angular Material themes should be created from a map

### ISSUE THREAD

**Issue by mischahaenen** [oblique-bit/oblique#97]
**See warning below:**
Angular Material themes should be created from a map containing the keys "color", "typography", and "density". The color value should be a map containing the palette values for "primary", "accent", and "warn". See https://material.angular.io/guide/theming for more information.

node_modules/@angular/material/core/theming/_theming.scss 185:5       define-light-theme()
node_modules/@oblique/oblique/styles/scss/oblique-material.scss 22:2  @use
node_modules/@oblique/oblique/styles/scss/oblique-core.scss 2:1       root stylesheet

Oblique version: 10.0.0

**Comment by gillerr** [comment]
Hi @mischahaenen 

Thanks for your report. We are already working on this, it will be solved with the next patch
