### ISSUE TITLE
Unsupported browser in google search

### ISSUE THREAD

**Issue by BenjaminHofstetter** [oblique-bit/oblique#98]
Google search shows for some routes(?) the content:
"Unsupported browser! Some features required for this application to run are not supported by your browser. Please note that the Swiss Confederation only ..."

Below is a funny query to detect oblique in *.admin.ch 

https://www.google.com/search?q=site:admin.ch+Unsupported+browser!+Some+features+required+for+this+application+to+run+are+not+supported+by+your+browser.+Please+note+that+the+Swiss+Confederation&lr=lang_de&client=safari&rls=en&tbs=lr:lang_1de&sxsrf=APwXEdfWiRw3PqsxIO84MtzFbuaPSrhOuw:1680126491013&ei=G7IkZKAzq4b27w_Vh6WYAQ&start=0&sa=N&ved=2ahUKEwjgrLL1joL-AhUrg_0HHdVDCRM4ChDy0wN6BAgFEAQ&biw=1512&bih=739&dpr=2

**Comment by gillerr** [comment]
Hi @BenjaminHofstetter 

Thank you for your feedback and sorry for the delay, we had our plates full for a while.

I took some time to analyze this problem and I don't understand what is happening. It seems that Google decides itself what is the best snippet of a website based on the content and the content meta tag.

I think our best bet would be to add `data-nosnippet` (https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#data-nosnippet-attr)  on the compatibility warning to ensure it won't be used as a snippet anymore

**Comment by nina-egger** [comment]
Note: Tracked in ticket OUI-3051

**Comment by nina-egger** [comment]
fixed with version 11.1.2
